### ISSUE TITLE
Docker Compose Cloud Error

### ISSUE THREAD

**Issue by Michelmat359** [CLARUS-HE-Project/ai-toolkit#2]
Good morning
we are getting an error when deploying the docker-compose in the CLOUD folder.

This error refers to the postgres image:

![imagen1](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/63206937/65e74eaf-35d0-4fab-bf05-a46ec4a9e53f)

The error returned is the following: 
2023-11-06 10:51:41.206 UTC [218] FATAL: database "mlflow" does not exist
2023-11-06 10:51:41.486 UTC [225] FATAL: role "airflow" does not exist

![imagen2](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/63206937/d5f03433-5173-4052-aacd-5c38efe42e6a)

Shortly after running, AIRFLOW stops working:
service "airflow-init" didn´t complete successfully: exit 137

![imagen3](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/63206937/ead904a5-1fd6-4f2c-9b91-3fb298176e8f)

We have tested it with wsl Ubuntu 20.04 and Ubuntu 22.04 and we get the same error. 
We didn't get this error on an Ubuntu server 22.04

**Comment by CLARUS-HE-Project** [comment]
Hi @Michelmat359 could you please perform the docker-compose up outside the venv? We have not tested this inside a virtual environment, but we do not face this problem if:
1. We launch it from WSL directly

and we use the following versions :
- docker-compose v2.17.3
- docker 23.0.5

**Comment by Michelmat359** [comment]
Good Afternoon, 
I tried to launch it from WSL directly, and I get the same error:
![image](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/63206937/d500201b-b7bc-4b3b-b4b8-56ca55f2cf85)

My Version:
![image](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/63206937/e69a6e83-f2d2-478c-979b-07d84012306a)

this error is repeated on two other computers via docker-desktop. There is no other service upload with docker. We have launched a docker system prune -a before.

I have tested on a clean Ubuntu 20.04 machine to raise the project, and it worked without problem. So the problem lies in some incompatibility of docker-desktop. Maybe we are missing some configuration not previously defined.

**Comment by Michelmat359** [comment]
Hello,
We have fixed it. It turns out that we have to change the shell interpreter to LF (\n) and we work in CRLF (\r\n). 
We have been able to launch it locally. Thanks for your time

**Comment by carlosbama3** [comment]
Hello,

We found other problems with the docker compose: 

-On the one hand, with dockerfile it is created an image where it installs the requirements
![image](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/129041405/5f6b1e5f-b14d-4d7a-b5a9-e00d609d2a50)

-On other hand, with docker compose it is generated another image which squashs the last one:
![image](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/129041405/98a4365a-f834-4841-81eb-99710de90abb)

-Finally, we have changed the image of apache airflow because for our models we need this  apache/airflow:2.3.0-python3.8
